title: Juan Ogdon — Portfolio
theme: minima
description: Portfolio of aerospace engineering projects — controls, CFD, simulation (Python/MATLAB/Simulink/OpenFOAM), mechanisms, and hardware prototyping.
markdown: kramdown
permalink: pretty
url: "https://juanogdon.github.io"
baseurl: "/Portfolio"   # your repo name, case-sensitive

# Define collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Navigation (optional)
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default
