title: Juan Ogdon — Portfolio
theme: minima
description: Portfolio of aerospace engineering projects — controls, CFD, simulation (Python/MATLAB/Simulink/OpenFOAM), mechanisms, and hardware prototyping.
markdown: kramdown
permalink: pretty

# Needed for project sites under /<repo>
url: "https://juanogdon.github.io"
baseurl: "/Portfolio"   # <-- EXACT repo name (case-sensitive)

# Build a 'projects' collection from docs/_projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Use a layout that shows the page title
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
